exports.users =[
    {
        userName:"rin",
        passWord:"123"
    },
    {
        userName:"thuThao",
        passWord:"123"
    },
    {
        userName:"NguyenBao",
        passWord:"123"
    },
    {
        userName:"sdi123",
        passWord:"123"
    },
    {
        userName:"ck098",
        passWord:"123"
    },
    {
        userName:"tony",
        passWord:"123"
    },
    {
        userName:"runNgun",
        passWord:"123"
    },
    {
        userName:"edward",
        passWord:"123"
    },
    {
        userName:"john",
        passWord:"123"
    },
    {
        userName:"kiss",
        passWord:"123"
    }
]